### ISSUE TITLE
flatpak?

### ISSUE THREAD

**Issue by anarcat** [every-day-things/citadel#5]
in #1, i saw some mention of appimage, has the idea of publishing this as a flatpak crossed your mind? right now it's what keeping me from trying the app, which otherwise looks pretty fantastic!

**Comment by phildenhoff** [comment]
Hi @anarcat — the idea of distribution in general has barely crossed my mind, sorry. Citadel is still _really early software_.

I don't have the interest to maintain many different build artifacts. I know that Tauri supports .deb & .appimage out of the box, so that's what I'm looking at. If either can be transformed to flatpaks, I'm happy to support those being built as well, but we don't have an automated build for anything yet.

In any case, in its current state, you probably don't want to use Citadel unless it's in dev mode!

Closing for now, but when we have automated builds, feel free to chime in again :)

**Comment by Victor239** [comment]
Can you reopen this issue? I'd like to subscribe to it so I can be notified when it's actually available as a feature. Until Citadel gets auto-updates whether it be by Flatpak or another means it's a deal-breaker for me but I'd still like to be informed when.

**Comment by phildenhoff** [comment]
@Victor239 I've added #11 if you want to wait for auto-updates

**Comment by Victor239** [comment]
Thanks!
